// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC92w7mwR1I9KofHCbQ6smXvYbSmYVMJ0Y',
    appId: '1:679326716390:web:fe450b6eef4125ddb74627',
    messagingSenderId: '679326716390',
    projectId: 'petapp-50785',
    authDomain: 'petapp-50785.firebaseapp.com',
    storageBucket: 'petapp-50785.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnGtAS7urkQE2XOvUxmT3EDibgV1bW7XI',
    appId: '1:679326716390:android:3c8b1b470ed89397b74627',
    messagingSenderId: '679326716390',
    projectId: 'petapp-50785',
    storageBucket: 'petapp-50785.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNGfMiGR-7BBypVw_zZAmYPT1yifabMvo',
    appId: '1:679326716390:ios:bc3c8fa13f4782f7b74627',
    messagingSenderId: '679326716390',
    projectId: 'petapp-50785',
    storageBucket: 'petapp-50785.firebasestorage.app',
    iosBundleId: 'com.example.petapp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNGfMiGR-7BBypVw_zZAmYPT1yifabMvo',
    appId: '1:679326716390:ios:bc3c8fa13f4782f7b74627',
    messagingSenderId: '679326716390',
    projectId: 'petapp-50785',
    storageBucket: 'petapp-50785.firebasestorage.app',
    iosBundleId: 'com.example.petapp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC92w7mwR1I9KofHCbQ6smXvYbSmYVMJ0Y',
    appId: '1:679326716390:web:e4b7ceacdc8ab51bb74627',
    messagingSenderId: '679326716390',
    projectId: 'petapp-50785',
    authDomain: 'petapp-50785.firebaseapp.com',
    storageBucket: 'petapp-50785.firebasestorage.app',
  );
}
